### ISSUE TITLE
Fix the nonworking "relative" css links (not so relative, VuePress must start them with slash, so specify base)

### ISSUE THREAD

**Issue by Poikilos** [poikilos/usingpython-website#1]

**Comment by poikilos** [comment]
See https://github.com/vuejs/vuepress/issues/796#issuecomment-737578607
- links to "https://poikilos.org/use-vuepress-to-build-static-html-files/"
- vuepress build was ignoring .vuepress/config.js because yarn changes the current directory. Run vuepress directly (not via yarn, presumably not via npm/npx) while in src instead (see export-html.sh).

**Comment by Poikilos** [comment]
See https://github.com/vuejs/vuepress/issues/1935#issuecomment-737614227
- links to "https://poikilos.org/use-vuepress-to-build-static-html-files/"
- vuepress build was ignoring .vuepress/config.js because yarn changes the current directory. Run vuepress directly (not via yarn, presumably not via npm/npx) while in src instead (see export-html.sh).
